nuaio_scraper/__init__.py
from flask import Flask
from redis import Redis
import rq


def create_app(config_file='settings.py'):
    app = Flask(__name__)
    app.config.from_pyfile(config_file)

    # Init extensions
    from nuaio_scraper.extensions import db
    db.init_app(app)

    app.redis = Redis.from_url(app.config['REDIS_URL'])
    app.rq_queue = rq.Queue(app.config['REDIS_QUEUE'], connection=app.redis)

    # Blueprints
    from nuaio_scraper.main import bp as main_bp
    app.register_blueprint(main_bp)

    from nuaio_scraper.errors import bp as errors_bp
    app.register_blueprint(errors_bp)

    return app

nuaio_scraper/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from nuaio_scraper.main import routes

nuaio_scraper/main/routes.py
from flask import render_template, request, redirect, url_for
from nuaio_scraper.main import bp
import subprocess
import os
import json
import pymssql


def helper_function(guia):
    if len(guia) == 12:

        subprocess.call(['venv/bin/scrapy', 'crawl', 'envia', '-a', f'guia={guia}', '-o', 'output.json'],
                        env=os.environ.copy())
        with open('output.json') as f:
            try:
                results = json.load(f)
            except json.decoder.JSONDecodeError:
                return render_template('not_found.html')
        os.remove('output.json')

        return render_template('consulta_guia.html', title='Consulta', results=results[0])

    elif len(guia) == 11:

        subprocess.call(['venv/bin/scrapy', 'crawl', 'coordinadora', '-a', f'guia={guia}', '-o', 'output.json'])
        with open('output.json') as f:
            try:
                results = json.load(f)
            except json.decoder.JSONDecodeError:
                os.remove('output.json')
                return render_template('not_found.html')

        os.remove('output.json')

        return render_template('consulta_guia.html', title='Consulta', results=results[0])

    elif len(guia) >= 8:
        conn = pymssql.connect(server='10.1.0.11', user='botsuministros', password='rpa2018.*', database='Weblogistica',
                               port='1433', as_dict=True)

        cursor = conn.cursor()

        query = ' '.join(("Select d.snumeroguia Guia,",
                          "e.snombre Estado_WL,",
                          "mo.motivo Causal_WL,",
                          "es.ESTADO Estado_SP,",
                          "d.sDestino as Destino,",
                          "concat(convert(varchar(10),sis.f_suc_des,103),' ', convert(varchar(10),sis.f_suc_des,108)) FechaRecibidoSucursal,",
                          "concat(convert(varchar(10),sis.Fchsalida,103),' ', convert(varchar(10),sis.Fchsalida,108)) FechaReparto,",
                          "concat(convert(varchar(10),sis.fechentre,103),' ', convert(varchar(10),sis.fechentre,108)) FechaEstadoFinal_SP,",
                          "concat(convert(varchar(10),sis.procesado,103),' ', convert(varchar(10),sis.procesado,108)) FechaIngresoCL, ",
                          "sis.imagen URL_SP,",
                          "concat(convert(varchar(10),d.dfechaestado,103),' ', convert(varchar(10),d.dfechaestado,108)) FechaEstado_WL,",
                          "concat(convert(varchar(10),d.dfechainiciogestion,103),' ', convert(varchar(10),d.dfechainiciogestion,108)) FechaTransporte",
                          "From tbdistribucion d",
                          "inner Join tbestado e On d.ncodigoestado = e.ncodigoestado",
                          "left Join Mdedb05.[db_sispostal].[dbo].[TBLGUIA] sis On d.sNumeroGuia=sis.guia",
                          "left join Mdedb05.[db_sispostal].dbo.TBLMOTDEVO mo on sis.tipodevo = mo.codmot",
                          "left Join Mdedb05.[db_sispostal].dbo.TBLESTADOS es On sis.estado = es.idste",
                          f"Where d.snumeroguia = '{guia}'"))

        cursor.execute(query)
        info = cursor.fetchone()

        conn.close()
        if not info:
            return render_template('not_found.html')
        status_list = []

        if info['FechaIngresoCL'].strip():
            status_list.append({
                'statusCode': '01',
                'statusDate': info['FechaIngresoCL'],
                'statusInfo': 'Pronto será recogido el pedido',
                'statusName': 'Orden creada'
            })
        elif info['FechaTransporte'].strip():
            status_list.append({
                'statusCode': '01',
                'statusDate': info['FechaTransporte'],
                'statusInfo': 'Pronto será recogido el pedido',
                'statusName': 'Orden creada'
            })
        if info['FechaRecibidoSucursal'].strip():
            status_list.append({
                'statusCode': '04',
                'statusDate': info['FechaRecibidoSucursal'],
                'statusInfo': 'El pedido se encuentra en la ciudad destino',
                'statusName': 'En bodega'
            })
        if info['FechaReparto'].strip():
            status_list.append({
                'statusCode': '05',
                'statusDate': info['FechaReparto'],
                'statusInfo': 'El pedido va en camino a su dirección destino',
                'statusName': 'En distribución'
            })
        if info['FechaEstadoFinal_SP'].strip():
            status_list.append({
                'statusCode': '06',
                'statusDate': info['FechaEstadoFinal_SP'],
                'statusInfo': info['Causal_WL'],
                'statusName': info['Estado_SP']
            })
        elif info['FechaEstado_WL'].strip():
            status_list.append({
                'statusCode': '06',
                'statusDate': info['FechaEstado_WL'],
                'statusInfo': info['Causal_WL'],
                'statusName': info['Estado_WL']
            })

        # sorted_status_list = sorted(status_list, key=lambda x: datetime.strptime(x['statusDate'], '%m/%d/%Y %H:%M:%S'))

        results = {
            'trackingNumber': info['Guia'],
            'shipFrom': 'La Estrella',
            'shipTo': info['Destino'],
            'imageURL': info['URL_SP'],
            'statusList': status_list
        }

        return render_template('consulta_guia.html', title='Consulta', results=results)

    else:
        return render_template('not_found.html')


@bp.route('/')
def index():
    return render_template('index.html', title='Nuaio Tracking Lite')


@bp.route('/consulta', methods=['POST', 'GET'])
def consulta():
    try:
        guia = request.form['numero_guia'].strip()
    except:
        return render_template('index.html')

    return helper_function(guia=guia)


@bp.route('/consulta/<guia>', methods=['GET'])
def consulta_guia(guia):
    return helper_function(guia=guia)


import pandas as pd
import numpy as np
import requests
from flask import send_from_directory

@bp.route('/cargar-orden', methods=['GET'])
def order_ingest_home():
    return render_template('order_ingest_home.html')


@bp.route('/cargar-orden/download', methods=['POST', 'GET'])
def order_ingest():
    print("test")
    print(request.files['input_file'])
    file = request.files['input_file']

    import pandas as pd
    import numpy as np
    import requests
    from itertools import chain

    '''
    def georreferenciar(address, city):
        url = "http://mdepyd07:9090/geolocation/api/georeference-address"
        headers = {
            'api-key': 'dc06617c-c21e-4792-91b8-0d9ef13369dd',
            'system-code': 'FAB-APP',
            'Content-Type': 'application/json'
        }
        payload = f'{{"address": "{address}","city": "{city}"}}'
        response = requests.request("POST", url, headers=headers, data=payload)
        try:
            geo_address = response.json()['geoRecord']['address']
        except:
            geo_address = ''
        return geo_address

    def geo_to_df(row):
        row['nueva_dir'] = georreferenciar(row['shipping_address_1'], row['shipping_city'])
        return row

    old_orders = pd.read_excel(
        'C:\\Users\\miguel.velasquez\\OneDrive - CADENA SA\\CadenaLabs\\eLogistics\\Order Ingest\\Cruces\\CONSOLIDADO PEDIDOS.xlsx')
    df = pd.read_excel(
        file,
        converters={'billing_phone': str})
    codigo_depts = pd.read_excel(
        'C:\\Users\\miguel.velasquez\\OneDrive - CADENA SA\\CadenaLabs\\eLogistics\\Order Ingest\\Cruces\\Cod ISO Dept.xlsx')
    codigo_divipola = pd.read_excel(
        'C:\\Users\\miguel.velasquez\\OneDrive - CADENA SA\\CadenaLabs\\eLogistics\\Order Ingest\\Cruces\\DIVIPOLA_20150630.xlsx',
        header=4)
    hist_column_names = ['Cedula', 'Nombre', 'Departamento', 'Direccion']
    historico_direcciones = pd.read_excel('C:\\Users\\miguel.velasquez\\OneDrive - CADENA '
                                          'SA\\CadenaLabs\\eLogistics\\Order Ingest\\Cruces\\Direcciones SAVVY.xlsx',
                                          header=None, names=hist_column_names)

    obligatory_columns = ['Convencion',
                          'Order ID',
                          'Columna1',
                          'Status',
                          'order_date',
                          'shipping_first_name',
                          'shipping_last_name',
                          'Cedula',
                          'shipping_address_1',
                          'billing_phone',
                          'shipping_city',
                          'shipping_state',
                          'shipping_country',
                          'item_product_id',
                          'item_name',
                          'item_quantity',
                          'order_total',
                          'shipping_total']

    savvy_catalog = {
        16196: ['T8.00.002402'],
        16186: ['T8.00.002401'],
        10012: ['T8.00.002397'],
        7962: ['T8.02.000547'],
        7954: ['T8.02.000548'],
        7661: ['T8.02.000546', 'T8.02.000545', 'T8.00.002396'],
        5584: ['T8.02.000546', 'T8.02.000545', 'T8.00.002398'],
        209: ['T8.02.000546'],
        200: ['T8.02.000545'],
        5939: ['T8.00.002396'],
        5280: ['T8.00.002398'],
        17990: ['T8.02.000546', 'T8.02.000545', 'T8.00.002397'],
        17994: ['T8.00.002402', 'T8.00.002401', 'T8.00.002398'],
        17980: ['T8.02.000547', 'T8.02.000548', 'T8.00.002396'],
        19770: ['T8.02.000547', 'T8.02.000545'],
        19794: ['T8.02.000548', 'T8.02.000545'],
        19789: ['T8.02.000547', 'T8.02.000546'],
        19796: ['T8.02.000548', 'T8.02.000546'],
        20129: ['T8.02.000555', 'T8.02.000553', 'T8.00.002412'],
        20125: ['T8.02.000554', 'T8.02.000554',
                'T8.02.000556', 'T8.02.000556',
                'T8.02.000557', 'T8.02.000557',

nuaio_scraper/templates/consulta_guia.html
{% extends "layout.html" %}
{% block content %}
    <div class="uk-section">
        <div class="uk-container">

            <h3>Consulta Guia</h3>

                <div class="uk-card uk-card-default uk-card-body uk-width-1-1">
                    <h3 class="uk-card-title">Número de guia: {{ results['trackingNumber'] }}</h3>
                    <p>Origen: {{ results['shipFrom'] }}</p>
                    <p>Destino: {{ results['shipTo'] }}</p>
                </div>
                {% for item in results['statusList'] %}
                <div class="uk-card uk-card-default uk-card-body uk-width-1-1">

                    <ul class="uk-list-circle">
                        <li class="uk-margin-auto-left" style="font-weight: bold;">{{ item['statusName'] }}</li>
                        <li class="uk-margin-auto-left">{{ item['statusDate'] }}</li>
                        {% if item['statusInfo'] is not none %}
                        <li class="uk-margin-auto-left">{{ item['statusInfo'] }}</li>
                        {% endif %}
                    </ul>
                </div>
                {% endfor %}
                {% if results['imageURL'] is not none%}
                <div class="uk-card uk-card-default uk-card-body uk-width-1-1">
                    <p class="uk-position-center">URL: <a href="{{ results['imageURL'] }}">Imagen de la guía</a></p>
                </div>
                {% endif %}
        </div>
    </div>
    <footer class="uk-section-xsmall uk-position-bottom">
        <div class="uk-container uk-position-center">
            <p>Made by <a class="uk-link-text" href="#" target="_blank">&#129514; CadenaLabs </a>&#8226; 2020</p>
        </div>
    </footer>
{% endblock content %}

nuaio_scraper/templates/index.html
{% extends "layout.html" %}
{% block content %}

    <h3 class="uk-card-title">Consulta de guia</h3>
    <form class="uk-form-horizontal uk-margin" method="POST" action="{{ url_for('main.consulta') }}">
        <div class="uk-margin uk-flex uk-flex-center">
            <input class="uk-input uk-width-5-6" type="text" name="numero_guia" placeholder="Número de guia">
            <button class="uk-button uk-button-primary" style="border-radius:20px" type="submit">Consulta</button>
        </div>
    </form>
    <footer class="uk-section-xsmall uk-position-bottom uk-position-absolute">
        <div class="uk-container uk-position-center">
            <p>Made by <a class="uk-link-text" href="#" target="_blank">&#129514; CadenaLabs </a>&#8226; 2020</p>
        </div>
    </footer>
{% endblock content %}

nuaio_scraper/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- UIkit CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/uikit.min.css') }}" />

    <!-- UIkit JS -->
    <script src="{{ url_for('static', filename='js/uikit.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/uikit-icons.min.js') }}"></script>

    <title>Nuaio Tracking Lite</title>

    <link rel="icon" href="https://nuaiolens.cadena.com.co/assets/img/favicon-4e9b3eb65f.ico">
</head>
<body>

    <div class="uk-background-cover uk-background-norepeat uk-height-viewport uk-flex uk-flex-center" style="background-image: url(https://nuaiolens.cadena.com.co/assets/img/fondo-tablet-vertical-a43e45e0ec.png)">
        <div class="uk-section">
            <div class="uk-container">
                <a href="{{ url_for('main.index') }}">
                    <img src="https://nuaiolens.cadena.com.co/assets/img/logo-nuaio-tracking-5036f304a7.png">
                </a>
                {% block content %} {% endblock %}
            </div>
        </div>
    </div>
</body>
</html>

nuaio_scraper/templates/not_found.html
{% extends "layout.html" %}
{% block content %}

    <h3 class="uk-card-title">Guia no encontrada</h3>
    <form class="uk-form-horizontal uk-margin" method="POST" action="{{ url_for('main.consulta') }}">
        <div class="uk-margin uk-flex uk-flex-center">
            <input class="uk-input uk-width-5-6" type="text" name="numero_guia" placeholder="Número de guia">
            <button class="uk-button uk-button-primary" style="border-radius:20px" type="submit">Consulta</button>
        </div>
    </form>
    <footer class="uk-section-xsmall uk-position-bottom uk-position-absolute">
        <div class="uk-container uk-position-center">
            <p>Made by <a class="uk-link-text" href="#" target="_blank">&#129514; CadenaLabs </a>&#8226; 2020</p>
        </div>
    </footer>
{% endblock content %}

nuaio_scraper/templates/order_ingest_download.html
{% extends "layout.html" %}
{% block content %}

    <h3 class="uk-card-title uk-text-center">Cargar Orden</h3>
    <form class="uk-form-horizontal uk-margin" method="POST" action="{{ url_for('main.order_ingest_dir') }}">
    <button class="uk-button uk-button-primary uk-align-center" style="border-radius:20px" type="submit">Descarga Dirección</button>
    </form>

    <form class="uk-form-horizontal uk-margin" method="POST" action="{{ url_for('main.order_ingest_ord') }}">
    <button class="uk-button uk-button-primary uk-align-center" style="border-radius:20px" type="submit">Descarga Pedidos</button>
    </form>

    <form class="uk-form-horizontal uk-margin" method="POST" action="{{ url_for('main.order_ingest_ceco') }}">
    <button class="uk-button uk-button-primary uk-align-center" style="border-radius:20px" type="submit">Descarga CeCo</button>
    </form>


    <footer class="uk-section-xsmall uk-position-bottom uk-position-absolute">
        <div class="uk-container uk-position-center">
            <p>Made by <a class="uk-link-text" href="#" target="_blank">&#129514; CadenaLabs </a>&#8226; 2020</p>
        </div>
    </footer>


{% endblock content %}

nuaio_scraper/templates/order_ingest_home.html
{% extends "layout.html" %}
{% block content %}

    <h3 class="uk-card-title uk-text-center">Cargar Orden</h3>
    <form class="uk-form-horizontal uk-margin" method="POST" action="{{ url_for('main.order_ingest') }}" enctype="multipart/form-data">
        <div class="js-upload uk-placeholder uk-text-center">
            <span uk-icon="icon: cloud-upload"></span>
            <span class="uk-text-middle">Carga el archivo de órdenes arrastrándolo aquí o</span>
            <div uk-form-custom>
                <input type="file", name="input_file">
                <span class="uk-link">selecciónalo</span>
            </div>
        </div>
    <button class="uk-button uk-button-primary uk-align-center" style="border-radius:20px" type="submit">Cargar</button>
    </form>
    <!--
    <script>
    var bar = document.getElementById('js-progressbar');

    UIkit.upload('.js-upload', {

        url: '',
        multiple: true,
        allow: '*.xlsx',

        beforeSend: function (environment) {
            console.log('beforeSend', arguments);

            // The environment object can still be modified here.
            // var {data, method, headers, xhr, responseType} = environment;

        },
        beforeAll: function () {
            console.log('beforeAll', arguments);
        },
        load: function () {
            console.log('load', arguments);
        },
        error: function () {
            console.log('error', arguments);
        },
        complete: function () {
            console.log('complete', arguments);
        },

        loadStart: function (e) {
            console.log('loadStart', arguments);

            bar.removeAttribute('hidden');
            bar.max = e.total;
            bar.value = e.loaded;
        },

        progress: function (e) {
            console.log('progress', arguments);

            bar.max = e.total;
            bar.value = e.loaded;
        },

        loadEnd: function (e) {
            console.log('loadEnd', arguments);

            bar.max = e.total;
            bar.value = e.loaded;
        },

        completeAll: function () {
            console.log('completeAll', arguments);

            setTimeout(function () {
                bar.setAttribute('hidden', 'hidden');
            }, 1000);

            alert('Upload Completed');
        }

    });

    </script>
    -->

    <footer class="uk-section-xsmall uk-position-bottom uk-position-absolute">
        <div class="uk-container uk-position-center">
            <p>Made by <a class="uk-link-text" href="#" target="_blank">&#129514; CadenaLabs </a>&#8226; 2020</p>
        </div>
    </footer>



{% endblock content %}